
-- 1. Ensure bucket exists and is PRIVATE
INSERT INTO storage.buckets (id, name, public)
VALUES ('ticket_photos', 'ticket_photos', false)
ON CONFLICT (id) DO UPDATE
SET public = false;

-- 2. Enable RLS on storage.objects
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- 3. Cleanup existing policies to avoid conflicts
DROP POLICY IF EXISTS "Admin Access" ON storage.objects;
DROP POLICY IF EXISTS "Public View" ON storage.objects;
DROP POLICY IF EXISTS "Give me everything" ON storage.objects;

-- 4. Create Policy: Admins (authenticated) have full access
CREATE POLICY "Admin Access" ON storage.objects
FOR ALL
TO authenticated
USING (bucket_id = 'ticket_photos')
WITH CHECK (bucket_id = 'ticket_photos');

-- 5. No Public Policy for SELECT means it is blocked by default.
-- Users must use Signed URLs generated by the Edge Function.
-- The Edge Function uses the Service Role key, which bypasses RLS.

-- 6. Ensure ticket_photos table exists and has correct structure (Path storage)
CREATE TABLE IF NOT EXISTS public.ticket_photos (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    ticket_id uuid NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    photo_url text NOT NULL, -- This stores the STORAGE PATH now
    uploaded_at timestamptz DEFAULT now()
);

-- 7. Grant permissions to anon/authenticated for the table (not storage) so they can read metadata
GRANT SELECT, INSERT ON public.ticket_photos TO anon, authenticated;
GRANT ALL ON public.ticket_photos TO service_role;
